# Generated by Django 6.0.6 on 2026-07-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browsing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="memberships",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="skills",
        ),
        migrations.AddField(
            model_name="preference",
            name="experience",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="preference",
            name="gym_frequency",
            field=models.CharField(
                choices=[
                    ("1_2", "1–2 times/week"),
                    ("3_4", "3–4 times/week"),
                    ("5_plus", "5+ times/week"),
                ],
                default="1_2",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="preference",
            name="preferred_workout_time",
            field=models.CharField(
                choices=[
                    ("early_morning", "Early Morning"),
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                    ("late_night", "Late Night"),
                ],
                default="morning",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="preference",
            name="training_styles",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="preference",
            name="goals",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="preference",
            name="user_activity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference",
                to="browsing.useractivity",
            ),
        ),
    ]
