# Generated by Django 6.0.6 on 2026-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browsing", "0002_remove_preference_memberships_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="preferred_workout_time",
        ),
        migrations.AddField(
            model_name="preference",
            name="preferred_workout_times",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
