# Generated by Django 6.0.6 on 2026-07-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0004_seed_gym_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='postal_codes',
        ),
        migrations.AddField(
            model_name='preference',
            name='location_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
