# Generated by Django 6.0.6 on 2026-07-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0005_remove_useractivity_postal_codes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
