# Generated by Django 6.0.6 on 2026-07-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0006_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20),
        ),
    ]
